import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';
import "./globals.css";
import layoutStyles from './styles/layout.module.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={layoutStyles.layoutHeader}>
          <Link href={"/"}>Noeasy App</Link>
        </div>
        <div className={layoutStyles.layoutContainer}>
          <div className={layoutStyles.layoutAside}>
            <div className={layoutStyles.layoutAsideMenu}>
              <div className={layoutStyles.layoutAsideTitle}>
                Common
              </div>
              <Link href={"/comm/menu"} className={layoutStyles.layoutAsideItem}>Menu</Link>
            </div>
            <div className={layoutStyles.layoutAsideMenu}>
              <div className={layoutStyles.layoutAsideTitle}>
                Example
              </div>
              <Link href={"/exam/counter"} className={layoutStyles.layoutAsideItem}>Counter</Link>
              <Link href={"/exam/table"} className={layoutStyles.layoutAsideItem}>Table</Link>
              <Link href={"/exam/typography"} className={layoutStyles.layoutAsideItem}>Typography</Link>
            </div>
          </div>
          <div className={layoutStyles.layoutContents}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
